### ISSUE TITLE
Add more projects!

### ISSUE THREAD

**Issue by alaouy** [arkhamdev/built-by-moroccan-devs#1]
Hey,
I'm Moroccan, I drink tea and my favorite dish is Couscous !
please add these projects !
http://screendy.mobi/
http://linkry.co/
http://enigma.io/

**Comment by arkhamdev** [comment]
All right, we'll take a look at these.
Thanks.

**Comment by kronik3r** [comment]
haha ba @alaouy,

I don't think that those projects are appropriate.
First, the soul reason why this project exists, is to show what Moroccan **Developers** have **Built**.
That link is important.

Second, some of those project are led by Moroccans but we are not sure that they have been built my Moroccans.

Finally, we are planning to add a feature where every project is linked to the author's twitter account.

So for those projects we are going to know who built them.

What you think guys?

**Comment by arkhamdev** [comment]
agree 100% and couldn't have said better.
any way i explained it to @alaouy this afternoon over coffee, he got it.

**Comment by kronik3r** [comment]
Great! glad to hear that :D

**Comment by moughamir** [comment]
Hey Folks!
I added new project check-out the **pull-request** :wink:
